name: Release Obsidian plugin

on:
  push:
    branches-ignore:
			- "main"

env:
  PLUGIN_NAME: obsidian-tldraw-plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Build
        id: build
        run: |
          npm install
          npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
					tag_name=$(git tag --sort version:refname | tail -n 1)
          echo "name=$tag_name" >> "$GITHUB_ENV"

			- name: test Upload zip file
				run: |
					echo "release-zip-name=${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip"
